name: Build

on:
  push:
    branches:
      - main
  pull_request:
defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      JAVA_OPTS: "-Xmx6G"
      SBT_OPTS: "-Dsbt.ci=true -Xss100M"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'sbt'

      - name: Test
        run: |
          sbt \
            "all headerCheck" \
            "all scalafmtSbtCheck" \
            "all scalafmtCheckAll" \
            "all scalafixAll --check" \
            "test"
